# Generated by Django 5.1.4 on 2025-10-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='employe', to='api.project'),
        ),
    ]
