# Generated by Django 5.1.4 on 2025-10-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
